//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.11 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2017.04.06 at 03:32:48 PM CEST 
//


package net.fluance.cockpit.domain.synlab;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType&gt;
 *   &lt;complexContent&gt;
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *       &lt;sequence&gt;
 *         &lt;element name="getStatutDemandeResult" type="{http://tempuri.org/}traceDemande" minOccurs="0"/&gt;
 *         &lt;element name="e" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/&gt;
 *       &lt;/sequence&gt;
 *     &lt;/restriction&gt;
 *   &lt;/complexContent&gt;
 * &lt;/complexType&gt;
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "getStatutDemandeResult",
    "e"
})
@XmlRootElement(name = "getStatutDemandeResponse")
public class GetStatutDemandeResponse {

    protected TraceDemande getStatutDemandeResult;
    protected String e;

    /**
     * Gets the value of the getStatutDemandeResult property.
     * 
     * @return
     *     possible object is
     *     {@link TraceDemande }
     *     
     */
    public TraceDemande getGetStatutDemandeResult() {
        return getStatutDemandeResult;
    }

    /**
     * Sets the value of the getStatutDemandeResult property.
     * 
     * @param value
     *     allowed object is
     *     {@link TraceDemande }
     *     
     */
    public void setGetStatutDemandeResult(TraceDemande value) {
        this.getStatutDemandeResult = value;
    }

    /**
     * Gets the value of the e property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getE() {
        return e;
    }

    /**
     * Sets the value of the e property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setE(String value) {
        this.e = value;
    }

}
