//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.11 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2017.04.06 at 03:32:48 PM CEST 
//


package net.fluance.cockpit.domain.synlab;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType&gt;
 *   &lt;complexContent&gt;
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *       &lt;sequence&gt;
 *         &lt;element name="OpenDeeplinkResult" type="{http://www.w3.org/2001/XMLSchema}boolean"/&gt;
 *         &lt;element name="strID" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/&gt;
 *       &lt;/sequence&gt;
 *     &lt;/restriction&gt;
 *   &lt;/complexContent&gt;
 * &lt;/complexType&gt;
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "openDeeplinkResult",
    "strID"
})
@XmlRootElement(name = "OpenDeeplinkResponse")
public class OpenDeeplinkResponse {

    @XmlElement(name = "OpenDeeplinkResult")
    protected boolean openDeeplinkResult;
    protected String strID;

    /**
     * Gets the value of the openDeeplinkResult property.
     * 
     */
    public boolean isOpenDeeplinkResult() {
        return openDeeplinkResult;
    }

    /**
     * Sets the value of the openDeeplinkResult property.
     * 
     */
    public void setOpenDeeplinkResult(boolean value) {
        this.openDeeplinkResult = value;
    }

    /**
     * Gets the value of the strID property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getStrID() {
        return strID;
    }

    /**
     * Sets the value of the strID property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setStrID(String value) {
        this.strID = value;
    }

}
