//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.11 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2017.04.06 at 03:32:48 PM CEST 
//


package net.fluance.cockpit.domain.synlab;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for patientComplet complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="patientComplet"&gt;
 *   &lt;complexContent&gt;
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *       &lt;sequence&gt;
 *         &lt;element name="strNCLI" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/&gt;
 *         &lt;element name="strZNOM" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/&gt;
 *         &lt;element name="strZPRE" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/&gt;
 *         &lt;element name="strCTIT" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/&gt;
 *         &lt;element name="strDNAI" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/&gt;
 *         &lt;element name="strDQNA" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/&gt;
 *         &lt;element name="strZAD1" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/&gt;
 *         &lt;element name="strZAD2" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/&gt;
 *         &lt;element name="strZCPO" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/&gt;
 *         &lt;element name="strZVIL" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/&gt;
 *         &lt;element name="strCOM1" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/&gt;
 *         &lt;element name="strCOM2" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/&gt;
 *         &lt;element name="strCOM3" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/&gt;
 *         &lt;element name="strNTE2" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/&gt;
 *         &lt;element name="strCPAY" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/&gt;
 *         &lt;element name="strCSEX" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/&gt;
 *         &lt;element name="strASSU" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/&gt;
 *         &lt;element name="strNST2" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/&gt;
 *         &lt;element name="strNTE1" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/&gt;
 *         &lt;element name="strZNJF" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/&gt;
 *       &lt;/sequence&gt;
 *     &lt;/restriction&gt;
 *   &lt;/complexContent&gt;
 * &lt;/complexType&gt;
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "patientComplet", propOrder = {
    "strNCLI",
    "strZNOM",
    "strZPRE",
    "strCTIT",
    "strDNAI",
    "strDQNA",
    "strZAD1",
    "strZAD2",
    "strZCPO",
    "strZVIL",
    "strCOM1",
    "strCOM2",
    "strCOM3",
    "strNTE2",
    "strCPAY",
    "strCSEX",
    "strASSU",
    "strNST2",
    "strNTE1",
    "strZNJF"
})
public class PatientComplet {

    protected String strNCLI;
    protected String strZNOM;
    protected String strZPRE;
    protected String strCTIT;
    protected String strDNAI;
    protected String strDQNA;
    protected String strZAD1;
    protected String strZAD2;
    protected String strZCPO;
    protected String strZVIL;
    protected String strCOM1;
    protected String strCOM2;
    protected String strCOM3;
    protected String strNTE2;
    protected String strCPAY;
    protected String strCSEX;
    protected String strASSU;
    protected String strNST2;
    protected String strNTE1;
    protected String strZNJF;

    /**
     * Gets the value of the strNCLI property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getStrNCLI() {
        return strNCLI;
    }

    /**
     * Sets the value of the strNCLI property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setStrNCLI(String value) {
        this.strNCLI = value;
    }

    /**
     * Gets the value of the strZNOM property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getStrZNOM() {
        return strZNOM;
    }

    /**
     * Sets the value of the strZNOM property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setStrZNOM(String value) {
        this.strZNOM = value;
    }

    /**
     * Gets the value of the strZPRE property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getStrZPRE() {
        return strZPRE;
    }

    /**
     * Sets the value of the strZPRE property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setStrZPRE(String value) {
        this.strZPRE = value;
    }

    /**
     * Gets the value of the strCTIT property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getStrCTIT() {
        return strCTIT;
    }

    /**
     * Sets the value of the strCTIT property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setStrCTIT(String value) {
        this.strCTIT = value;
    }

    /**
     * Gets the value of the strDNAI property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getStrDNAI() {
        return strDNAI;
    }

    /**
     * Sets the value of the strDNAI property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setStrDNAI(String value) {
        this.strDNAI = value;
    }

    /**
     * Gets the value of the strDQNA property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getStrDQNA() {
        return strDQNA;
    }

    /**
     * Sets the value of the strDQNA property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setStrDQNA(String value) {
        this.strDQNA = value;
    }

    /**
     * Gets the value of the strZAD1 property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getStrZAD1() {
        return strZAD1;
    }

    /**
     * Sets the value of the strZAD1 property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setStrZAD1(String value) {
        this.strZAD1 = value;
    }

    /**
     * Gets the value of the strZAD2 property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getStrZAD2() {
        return strZAD2;
    }

    /**
     * Sets the value of the strZAD2 property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setStrZAD2(String value) {
        this.strZAD2 = value;
    }

    /**
     * Gets the value of the strZCPO property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getStrZCPO() {
        return strZCPO;
    }

    /**
     * Sets the value of the strZCPO property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setStrZCPO(String value) {
        this.strZCPO = value;
    }

    /**
     * Gets the value of the strZVIL property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getStrZVIL() {
        return strZVIL;
    }

    /**
     * Sets the value of the strZVIL property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setStrZVIL(String value) {
        this.strZVIL = value;
    }

    /**
     * Gets the value of the strCOM1 property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getStrCOM1() {
        return strCOM1;
    }

    /**
     * Sets the value of the strCOM1 property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setStrCOM1(String value) {
        this.strCOM1 = value;
    }

    /**
     * Gets the value of the strCOM2 property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getStrCOM2() {
        return strCOM2;
    }

    /**
     * Sets the value of the strCOM2 property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setStrCOM2(String value) {
        this.strCOM2 = value;
    }

    /**
     * Gets the value of the strCOM3 property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getStrCOM3() {
        return strCOM3;
    }

    /**
     * Sets the value of the strCOM3 property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setStrCOM3(String value) {
        this.strCOM3 = value;
    }

    /**
     * Gets the value of the strNTE2 property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getStrNTE2() {
        return strNTE2;
    }

    /**
     * Sets the value of the strNTE2 property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setStrNTE2(String value) {
        this.strNTE2 = value;
    }

    /**
     * Gets the value of the strCPAY property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getStrCPAY() {
        return strCPAY;
    }

    /**
     * Sets the value of the strCPAY property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setStrCPAY(String value) {
        this.strCPAY = value;
    }

    /**
     * Gets the value of the strCSEX property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getStrCSEX() {
        return strCSEX;
    }

    /**
     * Sets the value of the strCSEX property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setStrCSEX(String value) {
        this.strCSEX = value;
    }

    /**
     * Gets the value of the strASSU property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getStrASSU() {
        return strASSU;
    }

    /**
     * Sets the value of the strASSU property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setStrASSU(String value) {
        this.strASSU = value;
    }

    /**
     * Gets the value of the strNST2 property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getStrNST2() {
        return strNST2;
    }

    /**
     * Sets the value of the strNST2 property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setStrNST2(String value) {
        this.strNST2 = value;
    }

    /**
     * Gets the value of the strNTE1 property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getStrNTE1() {
        return strNTE1;
    }

    /**
     * Sets the value of the strNTE1 property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setStrNTE1(String value) {
        this.strNTE1 = value;
    }

    /**
     * Gets the value of the strZNJF property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getStrZNJF() {
        return strZNJF;
    }

    /**
     * Sets the value of the strZNJF property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setStrZNJF(String value) {
        this.strZNJF = value;
    }

}
