//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.11 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2017.04.06 at 03:32:48 PM CEST 
//


package net.fluance.cockpit.domain.synlab;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for Patient complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="Patient"&gt;
 *   &lt;complexContent&gt;
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *       &lt;sequence&gt;
 *         &lt;element name="Titre" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/&gt;
 *         &lt;element name="DNAI" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/&gt;
 *         &lt;element name="refExterne" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/&gt;
 *         &lt;element name="NumClient" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/&gt;
 *         &lt;element name="Nom" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/&gt;
 *         &lt;element name="Prenom" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/&gt;
 *         &lt;element name="Prenom2" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/&gt;
 *         &lt;element name="DNA" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/&gt;
 *         &lt;element name="Civilite" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/&gt;
 *         &lt;element name="NomJ" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/&gt;
 *         &lt;element name="Sexe" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/&gt;
 *         &lt;element name="Adresse1" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/&gt;
 *         &lt;element name="Adresse2" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/&gt;
 *         &lt;element name="Ville" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/&gt;
 *         &lt;element name="CodePostal" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/&gt;
 *         &lt;element name="Tel1" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/&gt;
 *         &lt;element name="Tel2" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/&gt;
 *         &lt;element name="Tel3" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/&gt;
 *         &lt;element name="IDDEM" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/&gt;
 *         &lt;element name="IDEXEC" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/&gt;
 *         &lt;element name="ID" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/&gt;
 *         &lt;element name="NbDossierLie" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/&gt;
 *         &lt;element name="CodePays" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/&gt;
 *         &lt;element name="Pays" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/&gt;
 *       &lt;/sequence&gt;
 *     &lt;/restriction&gt;
 *   &lt;/complexContent&gt;
 * &lt;/complexType&gt;
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "Patient", propOrder = {
    "titre",
    "dnai",
    "refExterne",
    "numClient",
    "nom",
    "prenom",
    "prenom2",
    "dna",
    "civilite",
    "nomJ",
    "sexe",
    "adresse1",
    "adresse2",
    "ville",
    "codePostal",
    "tel1",
    "tel2",
    "tel3",
    "iddem",
    "idexec",
    "id",
    "nbDossierLie",
    "codePays",
    "pays"
})
public class Patient {

    @XmlElement(name = "Titre")
    protected String titre;
    @XmlElement(name = "DNAI")
    protected String dnai;
    protected String refExterne;
    @XmlElement(name = "NumClient")
    protected String numClient;
    @XmlElement(name = "Nom")
    protected String nom;
    @XmlElement(name = "Prenom")
    protected String prenom;
    @XmlElement(name = "Prenom2")
    protected String prenom2;
    @XmlElement(name = "DNA")
    protected String dna;
    @XmlElement(name = "Civilite")
    protected String civilite;
    @XmlElement(name = "NomJ")
    protected String nomJ;
    @XmlElement(name = "Sexe")
    protected String sexe;
    @XmlElement(name = "Adresse1")
    protected String adresse1;
    @XmlElement(name = "Adresse2")
    protected String adresse2;
    @XmlElement(name = "Ville")
    protected String ville;
    @XmlElement(name = "CodePostal")
    protected String codePostal;
    @XmlElement(name = "Tel1")
    protected String tel1;
    @XmlElement(name = "Tel2")
    protected String tel2;
    @XmlElement(name = "Tel3")
    protected String tel3;
    @XmlElement(name = "IDDEM")
    protected String iddem;
    @XmlElement(name = "IDEXEC")
    protected String idexec;
    @XmlElement(name = "ID")
    protected String id;
    @XmlElement(name = "NbDossierLie")
    protected String nbDossierLie;
    @XmlElement(name = "CodePays")
    protected String codePays;
    @XmlElement(name = "Pays")
    protected String pays;

    /**
     * Gets the value of the titre property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getTitre() {
        return titre;
    }

    /**
     * Sets the value of the titre property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setTitre(String value) {
        this.titre = value;
    }

    /**
     * Gets the value of the dnai property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getDNAI() {
        return dnai;
    }

    /**
     * Sets the value of the dnai property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setDNAI(String value) {
        this.dnai = value;
    }

    /**
     * Gets the value of the refExterne property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getRefExterne() {
        return refExterne;
    }

    /**
     * Sets the value of the refExterne property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setRefExterne(String value) {
        this.refExterne = value;
    }

    /**
     * Gets the value of the numClient property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getNumClient() {
        return numClient;
    }

    /**
     * Sets the value of the numClient property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setNumClient(String value) {
        this.numClient = value;
    }

    /**
     * Gets the value of the nom property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getNom() {
        return nom;
    }

    /**
     * Sets the value of the nom property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setNom(String value) {
        this.nom = value;
    }

    /**
     * Gets the value of the prenom property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getPrenom() {
        return prenom;
    }

    /**
     * Sets the value of the prenom property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setPrenom(String value) {
        this.prenom = value;
    }

    /**
     * Gets the value of the prenom2 property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getPrenom2() {
        return prenom2;
    }

    /**
     * Sets the value of the prenom2 property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setPrenom2(String value) {
        this.prenom2 = value;
    }

    /**
     * Gets the value of the dna property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getDNA() {
        return dna;
    }

    /**
     * Sets the value of the dna property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setDNA(String value) {
        this.dna = value;
    }

    /**
     * Gets the value of the civilite property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getCivilite() {
        return civilite;
    }

    /**
     * Sets the value of the civilite property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setCivilite(String value) {
        this.civilite = value;
    }

    /**
     * Gets the value of the nomJ property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getNomJ() {
        return nomJ;
    }

    /**
     * Sets the value of the nomJ property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setNomJ(String value) {
        this.nomJ = value;
    }

    /**
     * Gets the value of the sexe property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getSexe() {
        return sexe;
    }

    /**
     * Sets the value of the sexe property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setSexe(String value) {
        this.sexe = value;
    }

    /**
     * Gets the value of the adresse1 property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getAdresse1() {
        return adresse1;
    }

    /**
     * Sets the value of the adresse1 property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setAdresse1(String value) {
        this.adresse1 = value;
    }

    /**
     * Gets the value of the adresse2 property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getAdresse2() {
        return adresse2;
    }

    /**
     * Sets the value of the adresse2 property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setAdresse2(String value) {
        this.adresse2 = value;
    }

    /**
     * Gets the value of the ville property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getVille() {
        return ville;
    }

    /**
     * Sets the value of the ville property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setVille(String value) {
        this.ville = value;
    }

    /**
     * Gets the value of the codePostal property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getCodePostal() {
        return codePostal;
    }

    /**
     * Sets the value of the codePostal property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setCodePostal(String value) {
        this.codePostal = value;
    }

    /**
     * Gets the value of the tel1 property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getTel1() {
        return tel1;
    }

    /**
     * Sets the value of the tel1 property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setTel1(String value) {
        this.tel1 = value;
    }

    /**
     * Gets the value of the tel2 property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getTel2() {
        return tel2;
    }

    /**
     * Sets the value of the tel2 property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setTel2(String value) {
        this.tel2 = value;
    }

    /**
     * Gets the value of the tel3 property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getTel3() {
        return tel3;
    }

    /**
     * Sets the value of the tel3 property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setTel3(String value) {
        this.tel3 = value;
    }

    /**
     * Gets the value of the iddem property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getIDDEM() {
        return iddem;
    }

    /**
     * Sets the value of the iddem property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setIDDEM(String value) {
        this.iddem = value;
    }

    /**
     * Gets the value of the idexec property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getIDEXEC() {
        return idexec;
    }

    /**
     * Sets the value of the idexec property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setIDEXEC(String value) {
        this.idexec = value;
    }

    /**
     * Gets the value of the id property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getID() {
        return id;
    }

    /**
     * Sets the value of the id property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setID(String value) {
        this.id = value;
    }

    /**
     * Gets the value of the nbDossierLie property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getNbDossierLie() {
        return nbDossierLie;
    }

    /**
     * Sets the value of the nbDossierLie property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setNbDossierLie(String value) {
        this.nbDossierLie = value;
    }

    /**
     * Gets the value of the codePays property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getCodePays() {
        return codePays;
    }

    /**
     * Sets the value of the codePays property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setCodePays(String value) {
        this.codePays = value;
    }

    /**
     * Gets the value of the pays property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getPays() {
        return pays;
    }

    /**
     * Sets the value of the pays property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setPays(String value) {
        this.pays = value;
    }

}
