//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.11 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2017.04.06 at 03:32:48 PM CEST 
//


package net.fluance.cockpit.domain.synlab;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlSchemaType;
import javax.xml.bind.annotation.XmlType;
import javax.xml.datatype.XMLGregorianCalendar;


/**
 * <p>Java class for traceDemande complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="traceDemande"&gt;
 *   &lt;complexContent&gt;
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *       &lt;sequence&gt;
 *         &lt;element name="intStatutDemande" type="{http://www.w3.org/2001/XMLSchema}int"/&gt;
 *         &lt;element name="IDC" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/&gt;
 *         &lt;element name="DIV" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/&gt;
 *         &lt;element name="SDV" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/&gt;
 *         &lt;element name="dateCreation" type="{http://www.w3.org/2001/XMLSchema}dateTime"/&gt;
 *         &lt;element name="dateModification" type="{http://www.w3.org/2001/XMLSchema}dateTime"/&gt;
 *         &lt;element name="dateReception" type="{http://www.w3.org/2001/XMLSchema}dateTime"/&gt;
 *         &lt;element name="dateSuppression" type="{http://www.w3.org/2001/XMLSchema}dateTime"/&gt;
 *         &lt;element name="NDossLabo" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/&gt;
 *         &lt;element name="NST1" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/&gt;
 *         &lt;element name="NST2" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/&gt;
 *         &lt;element name="ID" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/&gt;
 *       &lt;/sequence&gt;
 *     &lt;/restriction&gt;
 *   &lt;/complexContent&gt;
 * &lt;/complexType&gt;
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "traceDemande", propOrder = {
    "intStatutDemande",
    "idc",
    "div",
    "sdv",
    "dateCreation",
    "dateModification",
    "dateReception",
    "dateSuppression",
    "nDossLabo",
    "nst1",
    "nst2",
    "id"
})
public class TraceDemande {

    protected int intStatutDemande;
    @XmlElement(name = "IDC")
    protected String idc;
    @XmlElement(name = "DIV")
    protected String div;
    @XmlElement(name = "SDV")
    protected String sdv;
    @XmlElement(required = true)
    @XmlSchemaType(name = "dateTime")
    protected XMLGregorianCalendar dateCreation;
    @XmlElement(required = true)
    @XmlSchemaType(name = "dateTime")
    protected XMLGregorianCalendar dateModification;
    @XmlElement(required = true)
    @XmlSchemaType(name = "dateTime")
    protected XMLGregorianCalendar dateReception;
    @XmlElement(required = true)
    @XmlSchemaType(name = "dateTime")
    protected XMLGregorianCalendar dateSuppression;
    @XmlElement(name = "NDossLabo")
    protected String nDossLabo;
    @XmlElement(name = "NST1")
    protected String nst1;
    @XmlElement(name = "NST2")
    protected String nst2;
    @XmlElement(name = "ID")
    protected String id;

    /**
     * Gets the value of the intStatutDemande property.
     * 
     */
    public int getIntStatutDemande() {
        return intStatutDemande;
    }

    /**
     * Sets the value of the intStatutDemande property.
     * 
     */
    public void setIntStatutDemande(int value) {
        this.intStatutDemande = value;
    }

    /**
     * Gets the value of the idc property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getIDC() {
        return idc;
    }

    /**
     * Sets the value of the idc property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setIDC(String value) {
        this.idc = value;
    }

    /**
     * Gets the value of the div property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getDIV() {
        return div;
    }

    /**
     * Sets the value of the div property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setDIV(String value) {
        this.div = value;
    }

    /**
     * Gets the value of the sdv property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getSDV() {
        return sdv;
    }

    /**
     * Sets the value of the sdv property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setSDV(String value) {
        this.sdv = value;
    }

    /**
     * Gets the value of the dateCreation property.
     * 
     * @return
     *     possible object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public XMLGregorianCalendar getDateCreation() {
        return dateCreation;
    }

    /**
     * Sets the value of the dateCreation property.
     * 
     * @param value
     *     allowed object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public void setDateCreation(XMLGregorianCalendar value) {
        this.dateCreation = value;
    }

    /**
     * Gets the value of the dateModification property.
     * 
     * @return
     *     possible object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public XMLGregorianCalendar getDateModification() {
        return dateModification;
    }

    /**
     * Sets the value of the dateModification property.
     * 
     * @param value
     *     allowed object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public void setDateModification(XMLGregorianCalendar value) {
        this.dateModification = value;
    }

    /**
     * Gets the value of the dateReception property.
     * 
     * @return
     *     possible object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public XMLGregorianCalendar getDateReception() {
        return dateReception;
    }

    /**
     * Sets the value of the dateReception property.
     * 
     * @param value
     *     allowed object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public void setDateReception(XMLGregorianCalendar value) {
        this.dateReception = value;
    }

    /**
     * Gets the value of the dateSuppression property.
     * 
     * @return
     *     possible object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public XMLGregorianCalendar getDateSuppression() {
        return dateSuppression;
    }

    /**
     * Sets the value of the dateSuppression property.
     * 
     * @param value
     *     allowed object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public void setDateSuppression(XMLGregorianCalendar value) {
        this.dateSuppression = value;
    }

    /**
     * Gets the value of the nDossLabo property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getNDossLabo() {
        return nDossLabo;
    }

    /**
     * Sets the value of the nDossLabo property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setNDossLabo(String value) {
        this.nDossLabo = value;
    }

    /**
     * Gets the value of the nst1 property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getNST1() {
        return nst1;
    }

    /**
     * Sets the value of the nst1 property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setNST1(String value) {
        this.nst1 = value;
    }

    /**
     * Gets the value of the nst2 property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getNST2() {
        return nst2;
    }

    /**
     * Sets the value of the nst2 property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setNST2(String value) {
        this.nst2 = value;
    }

    /**
     * Gets the value of the id property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getID() {
        return id;
    }

    /**
     * Sets the value of the id property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setID(String value) {
        this.id = value;
    }

}
